# Generated by Django 3.0.2 on 2020-02-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='allprofs',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='database',
            name='amp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='bandwidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='dedisp_H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='dedisp_profile',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='database',
            name='dedisp_z12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='dedisp_z2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='dedisp_z20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='dedisp_z6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='disp_H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='disp_profile',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='database',
            name='disp_z12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='disp_z2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='disp_z20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='disp_z6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='dm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='nbin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='nchan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='noise_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='ph0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='pulse_freq',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='start_freq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
