# Generated by Django 3.0.2 on 2020-02-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0003_auto_20200225_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_allprofs',
            new_name='allprofs1',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_dedisp_profile',
            new_name='dedisp_profile1',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_disp_profile',
            new_name='disp_profile1',
        ),
        migrations.AddField(
            model_name='pulseprofile',
            name='bin_allprofs1',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='pulseprofile',
            name='bin_dedisp_profile1',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='pulseprofile',
            name='bin_disp_profile1',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='allprofs',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='dedisp_profile',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='disp_profile',
            field=models.BinaryField(default=None),
        ),
    ]
