# Generated by Django 3.0.2 on 2020-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0004_auto_20200225_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulseprofile',
            name='allprofs',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='bin_allprofs1',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='bin_dedisp_profile1',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='bin_disp_profile1',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='dedisp_profile',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='disp_profile',
            field=models.BinaryField(),
        ),
    ]
