# Generated by Django 3.0.2 on 2020-02-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0005_auto_20200225_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_allprofs1',
            new_name='bin_immagine',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='allprofs1',
            new_name='immagine',
        ),
        migrations.RemoveField(
            model_name='pulseprofile',
            name='bin_dedisp_profile1',
        ),
        migrations.RemoveField(
            model_name='pulseprofile',
            name='bin_disp_profile1',
        ),
        migrations.RemoveField(
            model_name='pulseprofile',
            name='dedisp_profile1',
        ),
    ]
