# Generated by Django 3.0.2 on 2020-02-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_data_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='key',
            new_name='amp',
        ),
        migrations.AddField(
            model_name='data',
            name='allprofs',
            field=models.FileField(default=None, max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='data',
            name='bandwidth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='dedisp_H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='dedisp_profile',
            field=models.FileField(default=None, max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='data',
            name='dedisp_z12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='dedisp_z2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='dedisp_z20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='dedisp_z6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='disp_H',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='disp_profile',
            field=models.FileField(default=None, max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='data',
            name='disp_z12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='disp_z2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='disp_z20',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='disp_z6',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='dm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='nbin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='nchan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='noise_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='ph0',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pulse_freq',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='start_freq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
