# Generated by Django 3.0.2 on 2020-02-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_auto_20200220_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_allprofs',
            new_name='img_allprofs',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_dedisp_profile',
            new_name='img_dedisp_profile',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_disp_profile',
            new_name='img_disp_profile',
        ),
    ]
