# Generated by Django 3.0.2 on 2020-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0005_auto_20200220_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='img_allprofs',
            new_name='path_img_allprofs',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='img_dedisp_profile',
            new_name='path_img_dedisp_profile',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='img_disp_profile',
            new_name='path_img_disp_profile',
        ),
        migrations.AddField(
            model_name='pulseprofile',
            name='bin_img_allprofs',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='pulseprofile',
            name='bin_img_dedisp_profile',
            field=models.BinaryField(default=None),
        ),
        migrations.AddField(
            model_name='pulseprofile',
            name='bin_img_disp_profile',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='allprofs',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='dedisp_profile',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='disp_profile',
            field=models.BinaryField(default=None),
        ),
    ]
