# Generated by Django 3.0.2 on 2020-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0006_auto_20200225_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulseprofile',
            name='allprofs',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='bin_img_allprofs',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='bin_img_dedisp_profile',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='bin_img_disp_profile',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='dedisp_profile',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='pulseprofile',
            name='disp_profile',
            field=models.BinaryField(),
        ),
    ]
