# Generated by Django 3.0.2 on 2020-02-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0007_auto_20200225_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='bin_img_allprofs',
            new_name='bin_img',
        ),
        migrations.RenameField(
            model_name='pulseprofile',
            old_name='path_img_allprofs',
            new_name='path_img',
        ),
        migrations.RemoveField(
            model_name='pulseprofile',
            name='bin_img_dedisp_profile',
        ),
        migrations.RemoveField(
            model_name='pulseprofile',
            name='bin_img_disp_profile',
        ),
        migrations.RemoveField(
            model_name='pulseprofile',
            name='path_img_dedisp_profile',
        ),
        migrations.RemoveField(
            model_name='pulseprofile',
            name='path_img_disp_profile',
        ),
    ]
